# Generated by Django 4.2.27 on 2026-05-13 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='razorpay', max_length=32)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=64)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=64)),
                ('razorpay_signature', models.CharField(blank=True, max_length=200)),
                ('amount_paise', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='created', max_length=32)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
